CREATE TABLE FOUNDSHAREDREFERENCESTOCOLLECTIONTEST$DEPARTMENT (
  ID IDENTITY NOT NULL PRIMARY KEY
);

CREATE TABLE FOUNDSHAREDREFERENCESTOCOLLECTIONTEST$DEPARTMENTPHONE (
  ID IDENTITY NOT NULL PRIMARY KEY,
  DEPARTMENT_ID INT,
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES FOUNDSHAREDREFERENCESTOCOLLECTIONTEST$DEPARTMENT(ID)
);

CREATE TABLE FOUNDSHAREDREFERENCESTOCOLLECTIONTEST$USER (
 ID IDENTITY NOT NULL PRIMARY KEY,
 DEPARTMENT_ID INT,
 FOREIGN KEY (DEPARTMENT_ID) REFERENCES FOUNDSHAREDREFERENCESTOCOLLECTIONTEST$DEPARTMENT(ID)
);